(custom-set-variables
 '(c-basic-offset 4)
 '(case-fold-search t)
 '(column-number-mode t)
 '(current-language-environment "UTF-8")
 '(default-input-method "rfc1345")
 '(fill-column 79)
 '(global-font-lock-mode t nil (font-lock))
 '(indent-tabs-mode nil)
 '(keyboard-coding-system (quote utf-8))
 '(make-backup-files nil)
 '(mouse-wheel-follow-mouse t)
 '(mouse-wheel-mode t nil (mwheel))
 '(mouse-wheel-mode-hook (quote (ignore)))
 '(mouse-yank-at-point t)
 '(tab-width 4)
 '(transient-mark-mode t)
)
