#!/bin/sh

# File managed by puppet

src='/etc/openvpn/ca/distrib /etc/openvpn/ca/keys /srv/computations /srv/misc /srv/xapian'
dst='gestepc3.epfl.ch'
day=$(date +'%d')

for i in $src; do
  rsync -e "ssh -i /root/.ssh/id_rsa-ldapsync" -ah --delete --log-file /var/log/sync-datas/sync-${day}.log $i root@${dst}:$(dirname $i)/
done
