#!/usr/bin/perl
use strict;
$ENV{'PATH'} = '/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin';

my $fqdn = `host \$( ifconfig \$(ip -o route list scope global |awk '{print \$5}') | grep "inet " | awk '{print \$2}' | cut -d ':' -f 2 )` or exit(1) ;
open FH, "> /etc/apt/apt.conf.d/01proxy" or exit(2);

if ($fqdn =~ /wrk\.([a-z]{3})\.camptocamp\.com\.$/) {
  if ($1 == 'cby' || $1 == 'lsn') {
    print FH "Acquire::http::Proxy \"http://proxy.$1.camptocamp.com:3128\";;\n";
  }
} else {
  print FH '';
}
close FH;
exit(0)
